### ISSUE TITLE
Two question regarding seed

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/omock#108]
- Should seed be an option or the user could set it in advance?
```
cdm <- mockCdm(seed = 12345)
```
could be equivalent to:
```
set.seed(12345)
cdm <- mockCdm()
```

If we decide that seed is an argument (as It is now) I think we should change the default to seed = NULL as the behaviour by default changes the seed of random numbers and I don't think this is what the user would expect.

For you to consider @ilovemane

**Comment by ilovemane** [comment]
Should we take it out? @catalamarti @edward-burn
