### ISSUE TITLE
measurement table additional columns

### ISSUE THREAD

**Issue by nmercadeb** [OHDSI/omock#78]
For CohortConstructor it would be really helpful to have these 3 additional columns in the measurement table: `value_as_number`, `value_as_concept_id`, and `unit_concept_id`

**Comment by catalamarti** [comment]
- To make sure all tables contain all the columns:
```
omopgenerics::omopColumns("person", required = TRUE)
omopgenerics::omopColumns("person", required = FALSE)
omopgenerics:::fieldsTables
```

**Comment by ilovemane** [comment]
always create all the columns
